import React, { Component } from 'react';
import RecentDescription from'./RecentDescription';
import RecentImage from'./RecentImage';
import RecentMasterTitle from'./RecentMasterTitle';
import RecentSubtitle from'./RecentSubtitle';
import RecentTitle from'./RecentTitle';
import  './recent.css';



class Recent extends Component {
 

  render() {
   
          return (
           <div class Name="Recent">
                
                            
                   <div class="jss63 jss102 jss126">
                     <div class="jss1142 jss1111">
                       <div class="jss1139">
                         <div class="jss1141">
                           <svg class="jss307" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                             <path fill="none" d="M0 0h24v24H0z"></path>
                             <circle cx="6.18" cy="17.82" r="2.18"></circle>
                             <path d="M4 4.44v2.83c7.03 0 12.73 5.7 12.73 12.73h2.83c0-8.59-6.97-15.56-15.56-15.56zm0 5.66v2.83c3.9 0 7.07 3.17 7.07 7.07h2.83c0-5.47-4.43-9.9-9.9-9.9z"></path></svg>
                             <h2 class="jss271 jss288 jss1144">تازه‌های کارناوال</h2></div></div></div>
                             <div class="jss1272">
                               <div class="jss31 jss34 jss32 jss1282 jss1274 jss1273" data="[object Object]" relay="[object Object]">
                                 <div class="jss62"><div class="jss63 jss95"><div class="jss1289 jss1275">
                                   <a target="_blank" href="/blog/promotion-guaranteed-visa-banned">
                                     <img src="https://media.karnaval.ir/uploads/2019/06/schengen-visa-2.jpeg?size=400&amp;format=webp" class="jss1290"></img>
                                     </a></div>
                                     <div class="jss63 jss97 dFlex"><div class="jss1292 jss1281"><div class="jss62 jss70 jss81"><div class="jss63">
                                       <div class="jss1285"><a target="_blank" href="/blog/promotion-guaranteed-visa-banned">
                                         <h2 class="jss271 jss288 jss297 jss1286 jss1276">تبلیغ اخذ ویزای تضمینی ممنوع شد</h2></a></div></div>
                                         <div class="jss63"></div></div><div class="jss1287"><a class="jss1284" href="/author/bahaar1989" target="_blank">بهاره  فلاح</a>
                                         <a class="jss1284"> / </a><a class="jss1284"> 14 خرداد 1398</a></div><div class="jss1305 jss1279">
                                           <p class="jss271 jss279 jss1295">تبلیغ اخذ ویزای تضمینی توسط آژانس های مسافرتی از طرف اداره کل میراث فرهنگی استان تهران ممنوع شد...</p>
                                           <div class="jss1307 jss1280"></div></div><div class="jss1298"><div class="jss62 jss84 jss70 jss81"><div class="jss63"></div>
                                           <div class="jss63">
                                             <a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1296" tabindex="0" role="button" target="_blank" href="/blog/promotion-guaranteed-visa-banned">
                                               <span class="jss465">ادامه مطلب<svg class="jss307 jss1297" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                 <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span>
                                                 <span class="jss583"></span></a></div></div></div></div></div></div></div></div></div>
                                                 <div class="jss1308 jss1273"><a href="https://www.karnaval.ir/video/travel-oman" target="_blank"><div class="jss1309">
                                                   <img src="https://media.karnaval.ir/uploads/2019/04/bef5578a-8c14-4922-9ea5-1d84fbc7f124.jpg?size=800&amp;format=webp" class="jss1310" alt="">
                                                     <svg class="jss307 jss1311" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                       <path fill="none" d="M0 0h24v24H0z"></path>
                                                       <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z"></path></svg></img></div></a>
                                                       <div class="jss1313"><a href="https://www.karnaval.ir/video/travel-oman" target="_blank">
                                                         <h2 class="jss271 jss287 jss1315">سفر به عمان | سلطان نشینی زیبا</h2></a><div class="jss1317">
                                                           <a class="jss1318" href="https://www.karnaval.ir/video/travel-oman" target="_blank">نسیم امینی</a>
                                                           <a class="jss1318"> / </a><a class="jss1318"> 14 خرداد 1398</a><a class="jss1318"> / </a>
                                                           <a class="jss1318" target="_blank" href="https://www.karnaval.ir/blog/video/category/visit-tourist-attractions-video">گشت و گذار</a>
                                                           </div><div class="jsx-parser"><div class="jss1316">از میان مقاصد زیبای دنیا، یکی از کشورهای حوزه خلیج فارس را برگزیده ایم؛ می خواهیم با تماشای این ویدیو، سفر به عمان را تجربه کنیم و با این کشور کوچک، اما زیبا آشنا شویم. با یک برزیلی الاصل، به نام "میرو" همراه می شویم و تعدادی از&nbsp;جاذبه های عمان&nbsp;را از نظر می گذرانیم. میرو تاکنون به 246 کشور سفر کرده و عمان نیز یکی از مقاصد سفرش بوده است. او علاوه بر گشت و گذار در شهرهای این کشور، زمانی را هم در&nbsp;طبیعت عمان&nbsp;گذرانده...</div></div>
                                                           <div class="jss1319">
                                                             <a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1320" tabindex="0" role="button" target="_blank" href="https://www.karnaval.ir/video/travel-oman">
                                                               <span class="jss465">مشاهده ویدیو<svg class="jss307 jss1321" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                 <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path>
                                                                 <path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div>
                                                                 <div class="jss31 jss34 jss32 jss1282 jss1274 jss1273" data="[object Object]" relay="[object Object]"><div class="jss62">
                                                                   <div class="jss63 jss95"><div class="jss1289 jss1275">
                                                                     <a target="_blank" href="/blog/sun-rise-land-group-get-your-own-property-in-tbilisi">
                                                                       <img src="https://media.karnaval.ir/uploads/2019/06/b8045b88-4b21-4923-8227-27031199d22c.jpg?size=400&amp;format=webp" class="jss1290"></img></a></div></div>
                                                                       <div class="jss63 jss97 dFlex"><div class="jss1292 jss1281"><div class="jss62 jss70 jss81"><div class="jss63"><div class="jss1285">
                                                                         <a target="_blank" href="/blog/sun-rise-land-group-get-your-own-property-in-tbilisi">
                                                                           <h2 class="jss271 jss288 jss297 jss1286 jss1276">با سان رایس لند گروپ در تفلیس صاحب ملک شوید</h2></a></div></div>
                                                                           <div class="jss63"></div></div><div class="jss1287"><a class="jss1284" href="/author/advertising" target="_blank">واحد  تبلیغات</a>
                                                                           <a class="jss1284"> / </a><a class="jss1284"> 14 خرداد 1398</a></div><div class="jss1305 jss1279">
                                                                             <p class="jss271 jss279 jss1295">اگر تصمیم خود را برای خرید یا اجاره ملک در تفلیس گرفته اید و به دنبال یکی از راه های مطمئن برای تحقق بخشیدن به تصمیم تان هستید، وقت آن است که با سان رایس لند گروپ آشنا شوید...</p>
                                                                             <div class="jss1307 jss1280"></div></div>
                                                                             <div class="jss1298"><div class="jss62 jss84 jss70 jss81"><div class="jss63"></div>
                                                                             <div class="jss63"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1296" tabindex="0" role="button" target="_blank" href="/blog/sun-rise-land-group-get-your-own-property-in-tbilisi">
                                                                               <span class="jss465">ادامه مطلب<svg class="jss307 jss1297" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                                 <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path>
                                                                                 <path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div></div></div></div></div>
                                                                                 <div class="jss1308 jss1273">
                                                                                   <a href="https://www.karnaval.ir/blog/rules-turkey-airport" target="_blank">
                                                                                     <div class="jss1309">
                                                                                   <img src="https://media.karnaval.ir/uploads/2019/06/0d18ae98-a6ab-41f0-9e59-a1b2aaf982cc.jpg?size=800&amp;format=webp" class="jss1310" alt="">
                                                                                     </img></div></a><div class="jss1313"><a href="https://www.karnaval.ir/blog/rules-turkey-airport" target="_blank">
                                                                                       <h2 class="jss271 jss287 jss1315">قوانین فرودگاهی ترکیه | ضوابط ورود و خروج</h2></a><div class="jss1317">
                                                                                         <a class="jss1318" href="https://www.karnaval.ir/blog/rules-turkey-airport" target="_blank">زينب  شيرازی</a>
                                                                                         <a class="jss1318"> / </a><a class="jss1318"> 14 خرداد 1398</a><a class="jss1318"> / </a>
                                                                                         <a class="jss1318" target="_blank" href="https://www.karnaval.ir/blog/category/airport-rules">قوانین فرودگاهی</a></div>
                                                                                         <div class="jsx-parser">
                                                                                           <div class="jss1316">در اینجا می خواهیم بررسی کنیم که شما در هنگام سفر به ترکیه چه وسایلی را نمی توانید همراه داشته باشید و یا اگر دارید شامل چه تبصره هایی می شود، همچنین اشیایی که گاهی همراه داشتنشان برایمان شک برانگیز هستند را بررسی خواهیم کرد. بنابراین امروز به فرودگاه های ترکیه سر می زنیم تا با قوانین ورود و خروج به این کشور آشنا شویم.&nbsp;...</div></div>
                                                                                           <div class="jss1319">
                                                                                             <a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1320" tabindex="0" role="button" target="_blank" href="https://www.karnaval.ir/blog/rules-turkey-airport">
                                                                                               <span class="jss465">ادامه مطلب<svg class="jss307 jss1321" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                                                 <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path>
                                                                                                 <path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div>
                                                                                                 <div class="jss31 jss34 jss32 jss1282 jss1274 jss1273" data="[object Object]" relay="[object Object]">
                                                                                                   <div class="jss62"><div class="jss63 jss95"><div class="jss1289 jss1275">
                                                                                                     <a target="_blank" href="/blog/increase-airline-ticket-prices-ramadan">
                                                                                                       <img src="https://media.karnaval.ir/uploads/2019/06/dab158f7-b425-4dab-b73f-e465643f174e.jpg?size=400&amp;format=webp" class="jss1290"></img></a></div>
                                                                                                       <div class="jss63 jss97 dFlex"><div class="jss1292 jss1281"><div class="jss62 jss70 jss81"><div class="jss63">
                                                                                                         <div class="jss1285"><a target="_blank" href="/blog/increase-airline-ticket-prices-ramadan">
                                                                                                           <h2 class="jss271 jss288 jss297 jss1286 jss1276">افزایش قیمت بلیت هواپیما بعد از ماه رمضان</h2></a></div></div>
                                                                                                           <div class="jss63"></div></div><div class="jss1287"><a class="jss1284" href="/author/bahaar1989" target="_blank">بهاره  فلاح</a>
                                                                                                           <a class="jss1284"> / </a><a class="jss1284"> 13 خرداد 1398</a></div><div class="jss1305 jss1279">
                                                                                                             <p class="jss271 jss279 jss1295">دبیر انجمن صنفی دفاتر خدمات مسافرت هوایی، جهانگردی و زیارتی خراسان رضوی از افزایش قیمت بلیت شرکت‌های هواپیمایی بعد از ماه رمضان به دلیل افزایش تقاضای مردم خبر داد...</p>
                                                                                                             <div class="jss1307 jss1280"></div></div><div class="jss1298"><div class="jss62 jss84 jss70 jss81"><div class="jss63"></div>
                                                                                                             <div class="jss63"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1296" tabindex="0" role="button" target="_blank" href="/blog/increase-airline-ticket-prices-ramadan">
                                                                                                               <span class="jss465">ادامه مطلب<svg class="jss307 jss1297" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                                                                 <path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span>
                                                                                                                 <span class="jss583"></span></a></div></div></div></div></div></div></div>
                                                                                                                 <div class="jss1308 jss1273">
                                                                                                                   <a href="https://www.karnaval.ir/video/safari-zimbabwe-hwange-national-park" target="_blank">
                                                                                                                     <div class="jss1309"><img src="https://media.karnaval.ir/uploads/2019/06/6b8990e5-57f7-42f4-86fa-08f7aea9f61b.jpg?size=800&amp;format=webp" class="jss1310" alt="">
                                                                                                                       <svg class="jss307 jss1311" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                                                                         <path fill="none" d="M0 0h24v24H0z"></path>
                                                                                                                         <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z"></path></svg>
                                                                                                                         </img></div></a>
                                                                                                                         <div class="jss1313"><a href="https://www.karnaval.ir/video/safari-zimbabwe-hwange-national-park" target="_blank">
                                                                                                                           <h2 class="jss271 jss287 jss1315">سافاری در زیمبابوه | تجربه ای جذاب در پارک ملی هوانگ</h2></a>
                                                                                                                           <div class="jss1317"><a class="jss1318" href="https://www.karnaval.ir/video/safari-zimbabwe-hwange-national-park" target="_blank">نسیم امینی</a>
                                                                                                                           <a class="jss1318"> / </a><a class="jss1318"> 13 خرداد 1398</a><a class="jss1318"> / </a>
                                                                                                                           <a class="jss1318" target="_blank" href="https://www.karnaval.ir/blog/video/category/nature-video-hd">طبیعت HD</a></div>
                                                                                                                           <div class="jsx-parser"><div class="jss1316">نظرتان درباره تجربه متفاوت و جذاب&nbsp;سافاری در زیمبابوه&nbsp;چیست؟ به کمک ویدیوی امروز می خواهیم گشت و گذاری مجازی در دنیای حیوانات داشته باشیم و با&nbsp;حیات وحش آفریقا&nbsp;بیشتر آشنا شویم. اما پیش از آغاز سفرمان، کمی از کشور زیمبابوه و پارک ملی هوانگ که ویدیو در آن ضبط شده می گوییم و سپس به تماشای زندگی روزمره موجوداتی مانند زرافه، میمون ها، جغد، یوزپلنگ و ... می رویم. ما را در این گشت تماشایی همراهی کنید و برای خود خاطره...</div></div>
                                                                                                                           <div class="jss1319"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1320" tabindex="0" role="button" target="_blank" href="https://www.karnaval.ir/video/safari-zimbabwe-hwange-national-park"><span class="jss465">مشاهده ویدیو<svg class="jss307 jss1321" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div>
                                                                                                                           <div class="jss31 jss34 jss32 jss1282 jss1274 jss1273" data="[object Object]" relay="[object Object]"><div class="jss62"><div class="jss63 jss95"><div class="jss1289 jss1275"><a target="_blank" href="/blog/4-unique-cities-for-long-trips-reportage"><img src="https://media.karnaval.ir/uploads/2019/06/eb3c0eab-94ca-4987-a144-57640079bdb4.jpg?size=400&amp;format=webp" class="jss1290">
                                                                                                                             </img></a></div><div class="jss63 jss97 dFlex"><div class="jss1292 jss1281"><div class="jss62 jss70 jss81"><div class="jss63"><div class="jss1285"><a target="_blank" href="/blog/4-unique-cities-for-long-trips-reportage"><h2 class="jss271 jss288 jss297 jss1286 jss1276">4 شهر بی نظیر برای سفرهای طولانی مدت</h2></a></div></div><div class="jss63"></div></div><div class="jss1287"><a class="jss1284" href="/author/advertising" target="_blank">واحد  تبلیغات</a><a class="jss1284"> / </a><a class="jss1284"> 13 خرداد 1398</a></div><div class="jss1305 jss1279"><p class="jss271 jss279 jss1295">اگر از آن دسته افرادی هستید که سفرهای دو سه روزه را در حد شوخی کردن با واژه «مسافرت» قلمداد می‌کنید و دوست دارید مدتی در یک شهر بمانید توصیه‌های ما حتما به درد شما می‌خورد...</p><div class="jss1307 jss1280"></div></div><div class="jss1298"><div class="jss62 jss84 jss70 jss81"><div class="jss63"></div><div class="jss63"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1296" tabindex="0" role="button" target="_blank" href="/blog/4-unique-cities-for-long-trips-reportage"><span class="jss465">ادامه مطلب<svg class="jss307 jss1297" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div></div></div></div></div><div class="jss1308 jss1273"><a href="https://www.karnaval.ir/things-to-do/vakil-mosque-shiraz" target="_blank"><div class="jss1309"><img src="https://media.karnaval.ir/uploads/2018/03/FMf3waJhMcntpL4r-1520850172918.jpg?size=800&amp;format=webp" class="jss1310" alt="">
                                                                                                                               </img></div><div class="jss1313"><a href="https://www.karnaval.ir/things-to-do/vakil-mosque-shiraz" target="_blank"><h2 class="jss271 jss287 jss1315">مسجد وکیل شیراز | یادگاری ارزشمند از دوران زندیه</h2></a><div class="jss1317"><a class="jss1318" href="https://www.karnaval.ir/things-to-do/vakil-mosque-shiraz" target="_blank">بهاره  فلاح</a><a class="jss1318"> / </a><a class="jss1318"> 13 خرداد 1398</a><a class="jss1318"> / </a><a class="jss1318" target="_blank" href="https://www.karnaval.ir/blog/category/holy-places">سفرهای زیارتی و اماکن مقدس</a></div><div class="jsx-parser"><div class="jss1316">ورود اسلام به ایران، سرآغازی برای احداث بناهای مذهبی به شیوه اسلامی بود. هنرمندان ایرانی که مسلمان شده بودند، تمام تلاش خود را به کار گرفتند و عشق و هنر را در آمیختند تا بتوانند عبادتگاه خود را به بهترین شکل بسازند. امروزه حاصل کار و هنرمندی آنها در هر شهر و دیاری به چشم می خورد و چشم ها را به خود خیره می کند. مساجد به جای مانده از گذشته قصه های زیادی برای روایت کردن دارند و سرد و گرم روزگار را تاب آورده اند...</div></div><div class="jss1319"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1320" tabindex="0" role="button" target="_blank" href="https://www.karnaval.ir/things-to-do/vakil-mosque-shiraz"><span class="jss465">ادامه مطلب<svg class="jss307 jss1321" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div>
                                                                                                                               </a><div class="jss31 jss34 jss32 jss1282 jss1274 jss1273" data="[object Object]" relay="[object Object]"><div class="jss62"><div class="jss63 jss95"><div class="jss1289 jss1275"><a target="_blank" href="/blog/go-turkey-train-summer-98"><img src="https://media.karnaval.ir/uploads/2019/06/b0b78c69-3ac7-48ca-acde-1e9f7ca141ee.jpg?size=400&amp;format=webp" class="jss1290"></img>
                                                                                                                               </a></div><div class="jss63 jss97 dFlex"><div class="jss1292 jss1281"><div class="jss62 jss70 jss81"><div class="jss63"><div class="jss1285"><a target="_blank" href="/blog/go-turkey-train-summer-98"><h2 class="jss271 jss288 jss297 jss1286 jss1276">از اول تابستان 98 با قطار به ترکیه بروید</h2></a></div></div><div class="jss63"></div></div><div class="jss1287"><a class="jss1284" href="/author/bahaar1989" target="_blank">بهاره  فلاح</a><a class="jss1284"> / </a><a class="jss1284"> 12 خرداد 1398</a></div><div class="jss1305 jss1279"><p class="jss271 jss279 jss1295">سعید رسولی -معاون وزیر راه و شهرسازی- از راه اندازی قطار تهران-آنکارا از اول تیر ۹۸ خبر داد و درباره هزینه و مدت زمان سفر با این قطار توضیح داد...</p><div class="jss1307 jss1280"></div></div><div class="jss1298"><div class="jss62 jss84 jss70 jss81"><div class="jss63"></div><div class="jss63"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1296" tabindex="0" role="button" target="_blank" href="/blog/go-turkey-train-summer-98"><span class="jss465">ادامه مطلب<svg class="jss307 jss1297" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span></a></div></div></div></div></div></div></div><div class="jss1308 jss1273"><a href="https://www.karnaval.ir/video/aerial-video-singapore-city" target="_blank"><div class="jss1309"><img src="https://media.karnaval.ir/uploads/2019/04/d1b8d286-24b0-4837-b95a-a40683dd3449.jpg?size=800&amp;format=webp" class="jss1310" alt=""><svg class="jss307 jss1311" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path fill="none" d="M0 0h24v24H0z"></path>
                                                                                                                               <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 14.5v-9l6 4.5-6 4.5z"></path></svg>
                                                                                                                               </img></div><div class="jss1313"><a href="https://www.karnaval.ir/video/aerial-video-singapore-city" target="_blank"><h2 class="jss271 jss287 jss1315">ویدیو هوایی از شهر سنگاپور</h2></a><div class="jss1317"><a class="jss1318" href="https://www.karnaval.ir/video/aerial-video-singapore-city" target="_blank">نسیم امینی</a><a class="jss1318"> / </a><a class="jss1318"> 12 خرداد 1398</a><a class="jss1318"> / </a><a class="jss1318" target="_blank" href="https://www.karnaval.ir/blog/video/category/visit-tourist-attractions-video">گشت و گذار</a></div><div class="jsx-parser"><div class="jss1316">این بار می خواهیم یک&nbsp;ویدیو هوایی از شهر سنگاپور&nbsp;تماشا کنیم و شگفتی های این مقصد را از نظر بگذرانیم. بسیاری از&nbsp;جاذبه های سنگاپور&nbsp;که هر ساله گردشگران را به سوی این خطه می کشانند در پایتخت این کشور، یعنی شهر سنگاپور قرار گرفته اند و همین موضوع سبب شده تا امروز، این مکان را به عنوان مقصد سفر برگزینیم. می خواهیم بر فراز چندی از شاخص ترین&nbsp;دیدنی های سنگاپور&nbsp;پرواز کنیم و اینگونه، بیشتر با این شهر آشنا شویم. ما را در...</div></div><div class="jss1319"><a class="jss322 jss464 jss452 jss475 jss455 jss476 jss456 jss478 jss479 jss452 jss463 jss1320" tabindex="0" role="button" target="_blank" href="https://www.karnaval.ir/video/aerial-video-singapore-city"><span class="jss465">مشاهده ویدیو<svg class="jss307 jss1321" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation"><path d="M15.41 7.41L14 6l-6 6 6 6 1.41-1.41L10.83 12z"></path><path fill="none" d="M0 0h24v24H0z"></path></svg></span><span class="jss583"></span>
                                                                                                                               </a></div></div></a></div><button class="jss322 jss464 jss475 jss476 jss478 jss479 jss1277" tabindex="0" type="button">
                                                                                                                             <span class="jss465">بیشتر<svg class="jss307 jss1278" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                                                                                                                               <path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
                                                                                                                             <path fill="none" d="M0 0h24v24H0V0z"></path></svg></span><span class="jss583"></span></button></div></div>
                                                                                                                             </div>
                                                                                                                             </div>
                                                                                                                             </div>
                
           </div>

            );

        } 
        
   
}


export default Recent;